### ISSUE TITLE
[Bug]: Node 16 is required in Linux

### ISSUE THREAD

**Issue by arielj** [upgradejs/depngn#17]
### Expected Behavior

The `package.json` file specifies `"node": ">=10.0.0"` and no OS details, so it is expected that `npm install` works with old Node versions on Linux.

### Actual Behavior

`npm install` fails on Linux when using Node 14 with the following error:

```
$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

### Steps to Reproduce

1. Using Linux
2. Setup Node 14
3. Clone the project
4. `cd` into the project
5. run `npm install`

### Additional Information

Seems like there's a dependency on `fsevents` that can't be installed in Linux with Node 14.

`npm install` ends successfully using Node 16 on Linux.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JuanVqz** [comment]
Adding the following piece of code in the `package.json` installed all packages in nodejs 14

```json
  "optionalDependencies": {
    "fsevents": "^2.3.2"
  }
```
but now is complaining about another stuff

```bash
Error: Jest: Failed to parse the TypeScript config file /home/ombu/code/ombu/depngn/jest.config.ts
  Error: Jest: 'ts-node' is required for the TypeScript configuration files. Make sure it is installed
Error: Cannot find package 'ts-node' imported from /home/ombu/code/ombu/depngn/node_modules/jest-config/build/readConfigFileAndSetRootDir.js
    at readConfigFileAndSetRootDir (/home/ombu/code/ombu/depngn/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:136:13)
    at async readConfig (/home/ombu/code/ombu/depngn/node_modules/jest-config/build/index.js:216:18)
    at async readConfigs (/home/ombu/code/ombu/depngn/node_modules/jest-config/build/index.js:404:26)
    at async runCLI (/home/ombu/code/ombu/depngn/node_modules/@jest/core/build/cli/index.js:182:59)
    at async Object.run (/home/ombu/code/ombu/depngn/node_modules/jest-cli/build/cli/index.js:155:37)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! depngn@0.1.4 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the depngn@0.1.4 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ombu/.npm/_logs/2022-12-23T22_02_34_550Z-debug.log
```
