### ISSUE TITLE
[Bug]: `Error: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded`

### ISSUE THREAD

**Issue by adrienjoly** [upgradejs/depngn#42]
### Expected Behavior

Get a report about my dependencies.

### Actual Behavior

Got a `RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded` error.

### Steps to Reproduce

1. run `npx depngn` from our (private) codebase

### Additional Information

We cannot share the source code, but here are some specificities about our project:
- it currently runs on Node v14.21
- it has the following dependencies:
```
  "dependencies": {
    "@analytics/segment": "^1.1.0",
    "@apollo/client": "^3.4.7",
    "@expo-google-fonts/montserrat": "^0.2.2",
    "@expo/metro-config": "^0.3.21",
    "@expo/vector-icons": "^13.0.0",
    "@foodyssey/config-plugins-react-native-adjust": "^0.2.1",
    "@foodyssey/config-plugins-react-native-firebase": "^0.2.1",
    "@formatjs/intl-datetimeformat": "^4.2.5",
    "@formatjs/intl-locale": "^2.4.40",
    "@formatjs/intl-numberformat": "^7.2.5",
    "@formatjs/intl-pluralrules": "^4.1.5",
    "@joi/date": "^2.1.0",
    "@loadable/component": "^5.15.2",
    "@next/bundle-analyzer": "^12.1.0",
    "@portabletext/react": "^1.0.6",
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-firebase/app": "^14.5.1",
    "@react-native-firebase/auth": "^14.5.1",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/elements": "^1.2.1",
    "@react-navigation/native": "~6.0.0",
    "@react-navigation/stack": "~6.0.0",
    "@reduxjs/toolkit": "1.6.1",
    "@sanity/block-content-to-react": "^3.0.0",
    "@sanity/client": "^3.0.0",
    "@sanity/image-url": "^0.140.22",
    "@segment/analytics-react-native": "^2.3.2",
    "@segment/sovran-react-native": "^0.2.8",
    "@sentry/nextjs": "^7.30.0",
    "@sentry/react-native": "^3.1.1",
    "@spree/storefront-api-v2-sdk": "^4.5.4",
    "@storybook/react": "^6.5.16",
    "@storybook/react-native": "^5.3.27",
    "@stripe/react-stripe-js": "^1.4.1",
    "@stripe/stripe-js": "^1.35.0",
    "@stripe/stripe-react-native": "^0.14.0",
    "@unimodules/react-native-adapter": "~6.5.0",
    "@welldone-software/why-did-you-render": "^6.2.0",
    "analytics": "^0.7.13",
    "babel-plugin-inline-dotenv": "^1.6.0",
    "card-validator": "^8.1.0",
    "convert-svg-react": "^1.0.0-beta.7",
    "cors": "^2.8.5",
    "dayjs": "^1.11.0",
    "dotenv": "^10.0.0",
    "eslint": "^7.32.0",
    "expo": "^45.0.0",
    "expo-application": "~4.1.0",
    "expo-barcode-scanner": "~11.3.0",
    "expo-build-properties": "~0.2.0",
    "expo-constants": "~13.1.1",
    "expo-dev-client": "~1.0.1",
    "expo-device": "~4.2.0",
    "expo-filesystem-storage": "^1.0.3",
    "expo-firebase-analytics": "~7.0.0",
    "expo-font": "~10.1.0",
    "expo-linking": "~3.1.0",
    "expo-notifications": "~0.15.4",
    "expo-secure-store": "~11.2.0",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "expo-store-review": "~5.3.0",
    "expo-updates": "~0.13.4",
    "expo-web-browser": "~10.2.1",
    "firebase": "9.1.0",
    "graphql": "^15.5.1",
    "graphql-lodash": "^1.3.4",
    "i18n-js": "^3.8.0",
    "jest": "^26.6.3",
    "joi": "^17.6.0",
    "joi-browser": "^13.4.0",
    "lodash": "^4.17.20",
    "next": "^12.3.4",
    "next-compose-plugins": "^2.2.1",
    "next-images": "^1.8.4",
    "next-sanity-image": "^4.1.0",
    "next-transpile-modules": "^10.0.0",
    "oxide.ts": "^1.0.0",
    "prop-types": "^15.6.0",
    "ramda": "^0.27.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-adjust": "^4.29.6",
    "react-native-awesome-alerts": "^1.5.2",
    "react-native-background-timer": "^2.4.1",
    "react-native-circular-progress": "^1.3.7",
    "react-native-easy-grid": "^0.2.2",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-get-random-values": "~1.8.0",
    "react-native-google-places-autocomplete": "foodyssey/react-native-google-places-autocomplete#master",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-reanimated": "~2.8.0",
    "react-native-responsive-ui": "^2.1.5",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-snap-carousel": "4.0.0-beta.6",
    "react-native-svg": "12.3.0",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-tailwind.macro": "^1.3.3",
    "react-native-user-inactivity": "^1.2.0",
    "react-native-view-shot": "3.1.2",
    "react-native-web": "0.17.7",
    "react-native-web-swiper": "^2.2.2",
    "react-native-webview": "11.18.1",
    "react-redux": "^7.2.4",
    "react-svg": "^14.0.11",
    "react-test-renderer": "17.0.2",
    "recharts": "^2.2.0",
    "redux-debounce-thunk": "^1.0.1",
    "redux-persist": "^6.0.0",
    "redux-state-sync": "^3.1.4",
    "sentry-expo": "^4.2.0",
    "share-api-polyfill": "^1.0.21",
    "short-uuid": "^4.2.0",
    "use-deep-compare": "^1.1.0",
    "use-timer": "^2.0.1",
    "uuid": "^8.3.2",
    "yarn": "^1.22.11"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-class-properties": "^7.18.6",
    "@babel/plugin-transform-async-to-generator": "^7.14.5",
    "@babel/preset-env": "^7.1.6",
    "@expo/config-plugins": "^4.1.0",
    "@expo/next-adapter": "^4.0.13",
    "@firebase/app-types": "0.x",
    "@react-native-community/eslint-config": "^2.0.0",
    "@storybook/addon-actions": "^5.3",
    "@storybook/addon-knobs": "^5.3",
    "@storybook/addon-links": "^5.3",
    "@storybook/addon-ondevice-actions": "^5.3.23",
    "@storybook/addon-ondevice-knobs": "^5.3.26",
    "@storybook/react-native-server": "^5.3.23",
    "@testing-library/cypress": "^9.0.0",
    "@testing-library/jest-native": "^4.0.4",
    "@testing-library/react-hooks": "latest",
    "@testing-library/react-native": "latest",
    "@types/cors": "^2.8.12",
    "@types/dlv": "^1.0.0",
    "@types/faker": "^5.5.9",
    "@types/i18n-js": "^3.8.2",
    "@types/jest": "^27.0.1",
    "@types/lodash": "^4.14.172",
    "@types/node": "14",
    "@types/ramda": "^0.27.44",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.67.6",
    "@types/react-native-snap-carousel": "^3.8.4",
    "@types/react-redux": "^7.1.24",
    "@types/react-test-renderer": "^18.0.0",
    "@types/redux-state-sync": "^3.1.5",
    "@types/segment-analytics": "^0.0.34",
    "@types/uuid": "^8.3.1",
    "@typescript-eslint/eslint-plugin": "^5.51.0",
    "@typescript-eslint/parser": "^5.51.0",
    "babel-loader": "^8.3.0",
    "babel-plugin-inline-react-svg": "^2.0.1",
    "babel-plugin-macros": "^3.1.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "class-validator": "^0.13.2",
    "cypress": "^12.2.0",
    "cypress-firebase": "^2.2.3",
    "cypress-slow-down": "^1.2.1",
    "cypress-terminal-report": "^5.0.1",
    "eslint-config-universe": "^10.0.0",
    "eslint-plugin-jsx-expressions": "^1.3.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "faker": "^5.5.3",
    "firebase-admin": "^11.4.1",
    "husky": "^7.0.1",
    "jest-expo": "^46.0.1",
    "jest-fetch-mock": "^3.0.3",
    "nock": "^13.2.4",
    "node-mocks-http": "^1.11.0",
    "patch-package": "^6.4.7",
    "postcss": "^8.0.9",
    "postinstall-postinstall": "^2.1.0",
    "prettier": "^2.8.4",
    "react-native-storybook-loader": "^2.0.5",
    "require-from-string": "^2.0.2",
    "typescript": "^4.9.4",
    "webpack": "^5.75.0"
  },
```
- we use Yarn 1.22.19 to install those deps
- I ran the command on a M1 MacBook Pro, with a Node version installed using `nvm`

### What package manager are you seeing the problem with?

yarn

### Relevant log output

```shell
Error: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at /Users/adrienjoly/.npm/_npx/21383/lib/node_modules/depngn/dist/cli.cjs:7609:27
    at step (/Users/adrienjoly/.npm/_npx/21383/lib/node_modules/depngn/dist/cli.cjs:69:23)
    at Object.throw (/Users/adrienjoly/.npm/_npx/21383/lib/node_modules/depngn/dist/cli.cjs:50:53)
    at rejected (/Users/adrienjoly/.npm/_npx/21383/lib/node_modules/depngn/dist/cli.cjs:41:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kindoflew** [comment]
@adrienjoly  I _believe_ this is caused by our use of `exec` in `v0.3.0`.

Fortunately, this PR: #39, replaces `exec` with directly reading the data from file.

Unfortunately, that version hasn't been published yet and I can't publish new versions.

So, once @KostiantynPopovych or @etagwerker see this, they can publish a new version and that _should_ resolve this. (Also, @etagwerker, if you're concerned about publishing a new version without comprehensive tests, check out #40 👀. also also, hi! hope you're doing well!)

**Comment by KostiantynPopovych** [comment]
Hello @adrienjoly and @kindoflew, thank you for submitting and working on this issue. I have had a chance to work on this as well, I reproduced the issue locally, then tried the same with the latest changes from @kindoflew's #39, and they helped.

The new version (v0.4.0) was published, and you can try it on your project. Feel free to reach out to us back if that has not helped. Don't forget to use the latest published version - `npx depngn@latest` or `npx depngn@0.4.0`.

**Comment by adrienjoly** [comment]
The latest version works! Thank you!
